/** @type {import('next-sitemap').IConfig} */
module.exports = {
    siteUrl: 'https://www.linfungaccounting.com',
    generateRobotsTxt: true,
    robotsTxtOptions: {
      policies: [
        {userAgent: "*", disallow: "/unauthorized"},
        {userAgent: "*", disallow: "/admin/*"},
        {userAgent: "*", disallow: "/members/*"},
        {userAgent: "*", disallow: "/en/*"},
        {userAgent: "*", disallow: "/ch/*"},
        {userAgent: "*", disallow: "/services"},
        {userAgent: "*", disallow: "/wp-includes/*"},
        {userAgent: "*", disallow: "/tutorial-video"},
        {userAgent: "*", disallow: "/faq-1"},
        {userAgent: "*", disallow: "/baby"},
        {userAgent: "*", disallow: "/tech_support"},
        {userAgent: "*", disallow: "/login"},
        {userAgent: "*", disallow: "/giga-accounting-download-2"},
        {userAgent: "*", disallow: "/wp-login.php"},
        {userAgent: "*", disallow: "/members_account/*"},
        {userAgent: "*", disallow: "/giga-accounting-download"},
        {userAgent: "*", disallow: "/free-accounting-software-1"},
        {userAgent: "*", disallow: "/category/*"},
        {userAgent: "*", disallow: "/remotepc"},
        {userAgent: "*", disallow: "/comments/*"},
        {userAgent: "*", disallow: "/free-accounting-software-single-user-version-1"},
        {userAgent: "*", disallow: "/author/*"},
        {userAgent: "*", disallow: "/download_trial_iso"},
        {userAgent: "*", disallow: "/purchasesoftware"},
        {userAgent: "*", disallow: "/request_quotations"},
        {userAgent: "*", allow: "/"},
      ], 
    },
    exclude: ["/unauthorized","/admin/*","/members/*"],
  }